'use client';

import { useState, useMemo, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, Search, Plus, Upload, Download, Filter, QrCode, Eye, Loader2 } from 'lucide-react';
import { equipmentApi } from '@/lib/api/equipment';
import Image from 'next/image';
import DashboardLayout from '@/components/DashboardLayout';
import { useAuth } from '@/contexts/AuthContext';
// QR codes are generated by backend; no local/demo QR generation

interface Equipment {
  id: string;
  name: string;
  serialNumber: string;
  model: string;
  manufacturer: string;
  category: string;
  location: string;
  status: string;
  installDate: string;
  lastService?: string;
  qrCode?: string;
  qrCodeUrl?: string;
  qrCodeImageUrl?: string; // Data URL for the QR code image from database
  hasQRCodeImage?: boolean; // true only if image exists in database
}

function EquipmentListPageInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { organizationContext } = useAuth();
  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterManufacturer, setFilterManufacturer] = useState<string>('');
  const [generatingQR, setGeneratingQR] = useState<string | null>(null);
  const [bulkGenerating, setBulkGenerating] = useState(false);
  const [qrPreview, setQrPreview] = useState<{id: string; url: string} | null>(null);
  const [equipmentData, setEquipmentData] = useState<Equipment[]>([]);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [isClient, setIsClient] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isManufacturer, setIsManufacturer] = useState(false);
  const [manufacturerOrgId, setManufacturerOrgId] = useState<string | null>(null);

  // Check if user is a manufacturer and set org context
  useEffect(() => {
    if (organizationContext) {
      const isManuf = organizationContext.organization_type === 'manufacturer';
      setIsManufacturer(isManuf);
      setManufacturerOrgId(organizationContext.organization_id);
      
      console.log('[Equipment] Organization context:', {
        type: organizationContext.organization_type,
        id: organizationContext.organization_id,
        isManufacturer: isManuf
      });
    }
  }, [organizationContext]);

  // Read manufacturer from URL query parameter
  useEffect(() => {
    const manufacturer = searchParams.get('manufacturer');
    if (manufacturer) {
      setFilterManufacturer(manufacturer);
    }
  }, [searchParams]);

  // Fetch equipment data from API only (no mock fallback)
  useEffect(() => {
    setIsClient(true);
    
    const fetchEquipment = async () => {
      try {
        setLoading(true);
        setError(null);
        
        console.log('Fetching equipment from API...');
        const response = await equipmentApi.list({
          page: 1,
          page_size: 1000,
        });
        
        console.log('[Equipment Load] API Response:', response);
        
        // Map API response to component format
        const responseData: any = response;
        const equipmentItems = responseData.items || responseData.equipment || [];
        
        const mappedEquipment: Equipment[] = equipmentItems.map((item: any, index: number) => {
          // Check if QR code IMAGE exists in database (not just the qr_code field)
          const hasQRImage = !!item.qr_code_image;
          
          // Debug first few items
          if (index < 3) {
            console.log('[Equipment Load] Item:', {
              id: item.id,
              name: item.equipment_name,
              qr_code: item.qr_code,
              qr_code_url: item.qr_code_url,
              qr_code_image: item.qr_code_image ? 'EXISTS' : 'MISSING',
              hasQRCodeImage: hasQRImage
            });
          }
          
          return {
            id: item.id,
            name: item.equipment_name,
            serialNumber: item.serial_number,
            model: item.model_number || 'N/A',
            manufacturer: item.manufacturer_name,
            category: item.category || 'Unknown',
            location: item.installation_location || item.customer_name,
            status: item.status === 'operational' ? 'Active' : item.status === 'down' ? 'Inactive' : 'Maintenance',
            installDate: item.installation_date || item.created_at?.split('T')[0],
            lastService: item.last_service_date,
            qrCode: item.qr_code,
            qrCodeUrl: item.qr_code_url,
            qrCodeImageUrl: item.qr_code_image ? `data:image/png;base64,${item.qr_code_image}` : undefined,
            hasQRCodeImage: hasQRImage, // Check if qr_code_image exists in database
          };
        });
        
        const withQRImages = mappedEquipment.filter(e => e.hasQRCodeImage).length;
        console.log(`[Equipment Load] Loaded ${mappedEquipment.length} equipment items (${withQRImages} with QR code images)`);
        setEquipmentData(mappedEquipment);
      } catch (err) {
        console.error('Failed to fetch equipment from API:', err);
        setError('Failed to fetch equipment from API. Please ensure the backend is running and database has data.');
      } finally {
        setLoading(false);
      }
    };

    fetchEquipment();
  }, []);

  // Filter equipment based on search, status, and manufacturer
  const filteredEquipment = useMemo(() => {
    return equipmentData.filter(equipment => {
      const matchesSearch = searchQuery === '' || 
        equipment.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        equipment.serialNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
        equipment.model.toLowerCase().includes(searchQuery.toLowerCase()) ||
        equipment.manufacturer.toLowerCase().includes(searchQuery.toLowerCase()) ||
        equipment.category.toLowerCase().includes(searchQuery.toLowerCase()) ||
        equipment.location.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesStatus = filterStatus === 'all' || equipment.status.toLowerCase() === filterStatus.toLowerCase();
      
      const matchesManufacturer = filterManufacturer === '' || equipment.manufacturer === filterManufacturer;

      return matchesSearch && matchesStatus && matchesManufacturer;
    });
  }, [equipmentData, searchQuery, filterStatus, filterManufacturer]);

  const statusCounts = useMemo(() => {
    return equipmentData.reduce((acc, eq) => {
      acc[eq.status] = (acc[eq.status] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
  }, [equipmentData]);

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case 'active':
        return 'bg-green-100 text-green-800';
      case 'maintenance':
        return 'bg-yellow-100 text-yellow-800';
      case 'inactive':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const handleGenerateQR = async (equipmentId: string) => {
    try {
      setGeneratingQR(equipmentId);
      
      console.log('[QR Generation] Starting for equipment:', equipmentId);
      
      // Call real backend API to generate and store QR code
      const result: any = await equipmentApi.generateQRCode(equipmentId);
      
      console.log('[QR Generation] Success! Result:', result);
      
      // Instead of alert + reload, just reload to fetch updated data
      setTimeout(() => {
        console.log('[QR Generation] Reloading page to show updated QR code...');
        window.location.reload();
      }, 500);
      
    } catch (error) {
      console.error('[QR Generation] Failed:', error);
      alert(`Failed to generate QR code: ${error instanceof Error ? error.message : 'Unknown error'}\n\nPlease ensure backend API is reachable.`);
      setGeneratingQR(null);
    }
  };

  const handlePreviewQR = (equipment: Equipment) => {
    if (equipment.hasQRCodeImage && equipment.qrCodeImageUrl) {
      // Use the QR code image from database (base64 data URL)
      setQrPreview({ id: equipment.id, url: equipment.qrCodeImageUrl });
    }
  };

  const handleDownloadQR = async (equipmentId: string) => {
    try {
      await equipmentApi.downloadQRLabel(equipmentId);
    } catch (error) {
      alert(`Failed to download QR label: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  };


  const handleBulkGenerateQR = async () => {
    const confirmed = confirm("Generate QR codes for all equipment that doesn't have one? This may take a while.");
    if (!confirmed) return;

    try {
      setBulkGenerating(true);
      const result = await equipmentApi.bulkGenerateQRCodes();
      alert(result.message);
      window.location.reload();
    } catch (error) {
      alert(`Failed to bulk generate QR codes: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setBulkGenerating(false);
    }
  };

  const toggleSelectAll = (checked: boolean) => {
    if (checked) {
      const ids = new Set(filteredEquipment.map(e => e.id));
      setSelectedIds(ids);
    } else {
      setSelectedIds(new Set());
    }
  };

  const toggleSelectOne = (id: string, checked: boolean) => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (checked) next.add(id); else next.delete(id);
      return next;
    });
  };

  const handleGenerateSelected = async () => {
    if (selectedIds.size === 0) {
      alert('Please select at least one equipment item');
      return;
    }
    
    const count = selectedIds.size;
    const confirmed = confirm(`Generate QR codes for ${count} selected equipment items?`);
    if (!confirmed) return;
    
    try {
      setBulkGenerating(true);
      console.log(`[Bulk QR] Generating for ${count} equipment items...`);
      
      let success = 0;
      let failed = 0;
      
      for (const id of Array.from(selectedIds)) {
        try {
          console.log(`[Bulk QR] Generating for: ${id}`);
          await equipmentApi.generateQRCode(id);
          success++;
        } catch (e) {
          console.error(`[Bulk QR] Failed for ${id}:`, e);
          failed++;
        }
      }
      
      console.log(`[Bulk QR] Complete! Success: ${success}, Failed: ${failed}`);
      
      // Reload after a short delay
      setTimeout(() => {
        window.location.reload();
      }, 500);
      
    } catch (error) {
      console.error('[Bulk QR] Error:', error);
      alert('Failed to generate QR codes. Check console for details.');
      setBulkGenerating(false);
    }
  };
  // Show loading state during hydration
  if (!isClient || loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-blue-600" />
          <p className="text-gray-600">Loading equipment from API...</p>
        </div>
      </div>
    );
  }

  // Show error state
  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Card className="max-w-md w-full">
          <CardHeader>
            <CardTitle className="text-red-600">Error Loading Equipment</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 mb-4">{error}</p>
            <div className="space-y-2 text-sm text-gray-600">
              <p>Possible causes:</p>
              <ul className="list-disc list-inside space-y-1">
                <li>Backend not running or API base URL misconfigured</li>
                <li>Database connection issue</li>
                <li>No equipment data in database</li>
              </ul>
            </div>
            <Button 
              onClick={() => window.location.reload()} 
              className="mt-4 w-full"
            >
              Retry
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <Button
            variant="ghost"
            onClick={() => router.push('/dashboard')}
            className="mb-4"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
          
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Equipment Registry</h1>
              <p className="text-gray-600 mt-1">
                {isManufacturer 
                  ? "Your manufactured equipment (filtered automatically)"
                  : "Manage and monitor all medical equipment"}
              </p>
              {isManufacturer && (
                <div className="mt-2 inline-flex items-center px-3 py-1 bg-blue-50 border border-blue-200 rounded-md text-sm text-blue-700">
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  Showing only equipment manufactured by your organization
                </div>
              )}
            </div>
            
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                onClick={handleBulkGenerateQR}
                disabled={bulkGenerating}
              >
                {bulkGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <QrCode className="mr-2 h-4 w-4" />
                    Generate All QR Codes
                  </>
                )}
              </Button>
              <Button 
                variant="outline" 
                onClick={handleGenerateSelected}
                disabled={bulkGenerating || selectedIds.size === 0}
              >
                {bulkGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Selected...
                  </>
                ) : (
                  <>
                    <QrCode className="mr-2 h-4 w-4" />
                    Generate Selected
                  </>
                )}
              </Button>
              <Button variant="outline" onClick={() => router.push('/equipment/import')}>
                <Upload className="mr-2 h-4 w-4" />
                Import CSV
              </Button>
              <Button onClick={() => router.push('/equipment/new')}>
                <Plus className="mr-2 h-4 w-4" />
                Add Equipment
              </Button>
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Total Equipment</CardDescription>
              <CardTitle className="text-3xl">{equipmentData.length}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Active</CardDescription>
              <CardTitle className="text-3xl text-green-600">{statusCounts['Active'] || 0}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Under Maintenance</CardDescription>
              <CardTitle className="text-3xl text-yellow-600">{statusCounts['Maintenance'] || 0}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Inactive</CardDescription>
              <CardTitle className="text-3xl text-red-600">{statusCounts['Inactive'] || 0}</CardTitle>
            </CardHeader>
          </Card>
        </div>

        {/* Search and Filters */}
        <Card className="mb-6">
          <CardContent className="pt-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="Search equipment by name, serial number, model, manufacturer, category, or location..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
              <div className="flex gap-2">
                <select
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value)}
                  className="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="all">All Status</option>
                  <option value="active">Active</option>
                  <option value="maintenance">Maintenance</option>
                  <option value="inactive">Inactive</option>
                </select>
                <Button variant="outline">
                  <Download className="mr-2 h-4 w-4" />
                  Export
                </Button>
              </div>
            </div>
            
            {(searchQuery || filterStatus !== 'all' || filterManufacturer) && (
              <div className="mt-4 flex items-center gap-4">
                <div className="text-sm text-gray-600">
                  Showing {filteredEquipment.length} of {equipmentData.length} equipment
                </div>
                {filterManufacturer && (
                  <div className="flex items-center gap-2 px-3 py-1 bg-blue-50 border border-blue-200 rounded-md">
                    <span className="text-sm text-blue-700">
                      Filtered by manufacturer: <strong>{filterManufacturer}</strong>
                    </span>
                    <button
                      onClick={() => {
                        setFilterManufacturer('');
                        router.push('/equipment');
                      }}
                      className="text-blue-700 hover:text-blue-900"
                    >
                      ✕
                    </button>
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Equipment List */}
        {equipmentData.length === 0 ? (
          <Card>
            <CardContent className="py-12 text-center">
              <div className="text-gray-400 mb-4">
                <Upload className="h-12 w-12 mx-auto" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">No Equipment Found</h3>
              <p className="text-gray-600 mb-4">
                Get started by importing equipment from a CSV file or adding them manually.
              </p>
              <div className="flex justify-center gap-2">
                <Button onClick={() => router.push('/equipment/import')}>
                  <Upload className="mr-2 h-4 w-4" />
                  Import CSV
                </Button>
                <Button variant="outline" onClick={() => alert('Add equipment feature coming soon!')}>
                  <Plus className="mr-2 h-4 w-4" />
                  Add Manually
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b">
                    <tr>
                      <th className="px-6 py-3">
                        <input 
                          type="checkbox" 
                          aria-label="Select all"
                          checked={selectedIds.size > 0 && filteredEquipment.length > 0 && selectedIds.size === filteredEquipment.length}
                          onChange={(e) => toggleSelectAll(e.target.checked)}
                        />
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        QR Code
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Equipment
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Serial Number
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Category
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Location
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Status
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Last Service
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {filteredEquipment.map((equipment) => (
                      <tr key={equipment.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <input 
                            type="checkbox" 
                            checked={selectedIds.has(equipment.id)}
                            onChange={(e) => toggleSelectOne(equipment.id, e.target.checked)}
                            aria-label={`Select ${equipment.name}`}
                          />
                        </td>
                        {/* QR Code Column */}
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            {equipment.hasQRCodeImage && equipment.qrCodeImageUrl ? (
                              // Show QR code image from database with preview/download options
                              <div className="group relative">
                                <div 
                                  className="w-20 h-20 border-2 border-gray-200 rounded-md overflow-hidden cursor-pointer hover:border-blue-500 transition-colors bg-white"
                                  onClick={() => handlePreviewQR(equipment)}
                                  title="Click to preview full size"
                                >
                                  <img
                                    src={equipment.qrCodeImageUrl}
                                    alt={`QR Code for ${equipment.name}`}
                                    className="w-full h-full object-contain p-1"
                                    onError={(e) => {
                                      console.error('Failed to load QR image from database for', equipment.id);
                                    }}
                                  />
                                </div>
                                <div className="absolute hidden group-hover:flex flex-col gap-1 top-0 left-20 bg-white shadow-lg rounded-md p-2 z-10">
                                  <Button
                                    size="sm"
                                    variant="ghost"
                                    onClick={() => handlePreviewQR(equipment)}
                                    className="justify-start text-xs"
                                  >
                                    <Eye className="mr-1 h-3 w-3" />
                                    Preview
                                  </Button>
                                  <Button
                                    size="sm"
                                    variant="ghost"
                                    onClick={() => handleDownloadQR(equipment.id)}
                                    className="justify-start text-xs"
                                  >
                                    <Download className="mr-1 h-3 w-3" />
                                    Download
                                  </Button>
                                </div>
                              </div>
                            ) : (
                              // Show "Generate QR Code" button if no QR image in database
                              <Button
                                size="sm"
                                variant="outline"
                                onClick={() => handleGenerateQR(equipment.id)}
                                disabled={generatingQR === equipment.id}
                                className="w-20 h-20 flex flex-col items-center justify-center text-xs"
                              >
                                {generatingQR === equipment.id ? (
                                  <>
                                    <Loader2 className="h-4 w-4 animate-spin mb-1" />
                                    <span className="text-[10px]">Generating...</span>
                                  </>
                                ) : (
                                  <>
                                    <QrCode className="h-5 w-5 mb-1" />
                                    <span className="text-[10px] text-center">Generate QR</span>
                                  </>
                                )}
                              </Button>
                            )}
                          </div>
                        </td>
                        
                        {/* Equipment Details */}
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex flex-col">
                            <div className="text-sm font-medium text-gray-900">
                              {equipment.name}
                            </div>
                            <div className="text-xs text-gray-500">
                              {equipment.manufacturer} • {equipment.model}
                            </div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          {equipment.serialNumber}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          {equipment.category}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          {equipment.location}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusColor(equipment.status)}`}>
                            {equipment.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {equipment.lastService || 'N/A'}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <div className="flex items-center justify-end gap-2">
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => router.push(`/equipment/${equipment.id}`)}
                            >
                              View
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => {
                                const code = equipment.qrCode || equipment.id;
                                const url = code ? `/service-request?qr=${encodeURIComponent(code)}` : '/service-request';
                                router.push(url);
                              }}
                            >
                              Create Service Request
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      {/* QR Code Preview Modal */}
      {qrPreview && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4"
          onClick={() => setQrPreview(null)}
        >
          <div 
            className="bg-white rounded-lg shadow-xl max-w-md w-full p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">QR Code Preview</h3>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setQrPreview(null)}
              >
                ✕
              </Button>
            </div>
            
            <div className="flex justify-center mb-4">
              <div className="w-64 h-64 border-2 border-gray-200 rounded-md p-4 bg-white">
                <Image
                  src={qrPreview.url}
                  alt="QR Code"
                  width={256}
                  height={256}
                  className="w-full h-full object-contain"
                  unoptimized
                />
              </div>
            </div>

            <div className="text-center text-sm text-gray-500 mb-4">
              Equipment ID: {qrPreview.id}
            </div>

            <div className="flex gap-2">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => handleDownloadQR(qrPreview.id)}
              >
                <Download className="mr-2 h-4 w-4" />
                Download PDF Label
              </Button>
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => {
                  window.open(qrPreview.url, '_blank');
                }}
              >
                <Eye className="mr-2 h-4 w-4" />
                Open in New Tab
              </Button>
            </div>
          </div>
        </div>
      )}
    </DashboardLayout>
  );
}

export default function EquipmentListPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-gray-50 flex items-center justify-center"><div className="text-center"><Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-blue-600" /><p className="text-gray-600">Loading...</p></div></div>}>
      <EquipmentListPageInner />
    </Suspense>
  );
}



